data_cfg:
  dataset_name: CCVID
  dataset_root: ./datasets/CCVID_PROCESS_PKL
  dataset_partition: ./datasets/CCVID_PROCESS_PKL/ccvid_split.json
  num_workers: 1
  data_in_use: [True, False]  # [heatmap, silhouette] — CCVID는 skeleton 기반이므로 sil은 False
  remove_no_gallery: false
  test_dataset_name: CCVID

evaluator_cfg:
  enable_float16: true
  restore_ckpt_strict: true
  restore_hint: 180000
  save_name: SkeletonGaitPP
  eval_func: evaluate
  sampler:
    batch_shuffle: false
    batch_size: 4
    sample_type: all_ordered
    frames_all_limit: 720
  metric: euc
  transform:
    - type: BaseSilCuttingTransform

loss_cfg:
  - loss_term_weights: 1.0
    margin: 0.2
    type: TripletLoss
    log_prefix: triplet
  - loss_term_weights: 1.0
    scale: 16
    type: CrossEntropyLoss
    log_prefix: softmax
    log_accuracy: true

model_cfg:
  model: SkeletonGaitPP
  Backbone:
    in_channels: 3  # 일반적으로 JointMap, LimbMap, SkeletonMap을 RGB처럼 3채널 처리
    blocks:
      - 1
      - 4
      - 4
      - 1
    C: 2
  SeparateBNNecks:
    class_num: 226  # CCVID 내 피험자 수에 따라 조정

optimizer_cfg:
  lr: 0.1
  momentum: 0.9
  solver: SGD
  weight_decay: 0.0005

scheduler_cfg:
  gamma: 0.1
  milestones:
    - 80000
    - 120000
    - 150000
  scheduler: MultiStepLR

trainer_cfg:
  enable_float16: true
  fix_BN: false
  log_iter: 100
  restore_ckpt_strict: true
  restore_hint: 0
  save_iter: 30000
  save_name: SkeletonGaitPP
  sync_BN: true
  total_iter: 180000
  sampler:
    batch_shuffle: true
    batch_size:
      - 16  # ID 수
      - 4   # 시퀀스 수
    frames_num_fixed: 30
    frames_skip_num: 4
    sample_type: fixed_ordered
    type: TripletSampler
  transform:
    - type: Compose
      trf_cfg:
        - type: RandomPerspective
          prob: 0.2
        - type: BaseSilCuttingTransform
        - type: RandomHorizontalFlip
          prob: 0.2
        - type: RandomRotate
          prob: 0.2
