data_cfg:
  dataset_name: CCVID
  dataset_root: ./datasets/CCVID_PROCESS_PKL
  dataset_partition: ./datasets/CCVID_PROCESS_PKL/ccvid_split.json
  partition_by_pid: true
  num_workers: 1
  data_in_use: [true, true]
  remove_no_gallery: false
  test_dataset_name: CCVID

evaluator_cfg:
  enable_float16: true
  restore_ckpt_strict: true
  restore_hint: 60000
  save_name: SkeletonGaitPP
  eval_func: evaluate_CCPG
  sampler:
    batch_shuffle: false
    batch_size: [4, 2]  # [total_sequences_per_batch, num_sequences_per_id]
    sample_type: all_ordered
    frames_all_limit: 720
  metric: euc
  transform:
    - type: BaseSilCuttingTransform

loss_cfg:
  - loss_term_weights: 1.0
    margin: 0.2
    type: TripletLoss
    log_prefix: triplet
  - loss_term_weights: 1.0
    scale: 16
    type: CrossEntropyLoss
    log_prefix: softmax
    log_accuracy: true

model_cfg:
  model: SkeletonGaitPP
  Backbone:
    in_channels: 2        # 스켈레톤 채널(보통 joint+limb 2채널)
    blocks: [1, 1, 1, 1]
    C: 2
  SeparateBNNecks:
    class_num: 3          # 데이터셋 내 ID 수에 맞게 조절

optimizer_cfg:
  lr: 0.1
  momentum: 0.9
  solver: SGD
  weight_decay: 0.0005

scheduler_cfg:
  gamma: 0.1
  milestones: [20000, 30000, 40000]
  scheduler: MultiStepLR

trainer_cfg:
  dist: false
  enable_float16: false
  fix_BN: false
  log_iter: 100
  restore_ckpt_strict: true
  restore_hint: 0
  save_iter: 10000
  save_name: SkeletonGaitPP_CCVID
  sync_BN: false
  total_iter: 60000
  sampler:
    batch_shuffle: true
    batch_size: [4, 2]  # [total_sequences_per_batch, num_sequences_per_id]
    frames_num_fixed: 6
    frames_skip_num: 1
    sample_type: fixed_ordered
    type: TripletSampler
  transform:
    - type: Compose
      trf_cfg:
        - type: RandomPerspective
          prob: 0.2
        - type: BaseSilCuttingTransform
        - type: RandomHorizontalFlip
          prob: 0.2
        - type: RandomRotate
          prob: 0.2
